site_name: Knowledge Base

nav:
    - Home: index.md
    - Setting up Kali Linux: Virtual_Lab_Setup.md
    - NahamSec Recon Session 1 Notes: nahamsec/recon_session_1.md
    - NahamSec Recon Session 2 Notes: nahamsec/recon_session_2.md
    - BugBountyNotes Mentoring Session: bugbountynotes/firstlivementoring.md
    - BugBountyNotes FastFoodHacking Session 1: bugbountynotes/fastfoodhackingsession1.md
    - BugBountyNotes Challenge Session 1: bugbountynotes/challengesession1.md
    - BugBountyNotes Filter Bypass Session: bugbountynotes/filterbypass.md
    - Tomnomnom Q&A Session: tomnomnom/session1.md
    - ippsec tmux Session: ippsec/tmux.md
    - Stok IDOR Session:  idor.md
    - Tomnomnom Vim Tutorial: vim_tutorial.md
theme: readthedocs
